name:                lev
version:             0.1.0.0
github:              "PROTEINE-INSAIDERS/lev"
license:             BSD3
author:              "Stanislav Chernichkin"
maintainer:          "schernichkin@gmail.com"
copyright:           "2022 Stanislav Chernichkin"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
category:            Serialization

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/PROTEINE-INSAIDERS/lev#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- containers
- ghc-prim
- indexed
- mtl
- primitive
- singletons 
- singletons-th
- template-haskell
# - th-orphans
- th-utilities
- unliftio

# TODO: move benchmarks to bench/ directory and remove this dependencies
- criterion
- store
- deepseq
- vector
- flat

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  lev-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lev
    - criterion
    - store
    - deepseq

tests:
  lev-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lev

benchmarks:
  lev-bench:
    main:                Bench.hs
    source-dirs:         bench
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N1 
    - -with-rtsopts=-s 
    - -with-rtsopts=-qg
    dependencies:
    - lev
    - criterion
    - store